/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.WorkAreas.FacultyRole;

import Business.Business;
import UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp.ManagePersonsJPanel;
import javax.swing.JPanel;
import UserInterface.WorkAreas.FacultyRole.FacultyRoleWorkResp02.CourseManagementJPanel;
import Business.Profiles.FacultyProfile;

/**
 *
 * @author kal
 */


public class FacultyWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    FacultyProfile facultyProfile;

    /**
     * Creates new form UnitRiskWorkArea
     */

    public FacultyWorkAreaJPanel(Business b, FacultyProfile fp, JPanel clp) {

        business = b;
        facultyProfile = fp;
        this.CardSequencePanel = clp;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCourseManagement = new javax.swing.JButton();
        btnProfileManagement = new javax.swing.JButton();
        btnStudentManagement = new javax.swing.JButton();
        btnPerformance = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTution = new javax.swing.JButton();

        setForeground(new java.awt.Color(51, 51, 51));

        btnCourseManagement.setBackground(new java.awt.Color(102, 153, 255));
        btnCourseManagement.setFont(getFont());
        btnCourseManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseManagement.setText("Course Management");
        btnCourseManagement.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCourseManagement.setMaximumSize(new java.awt.Dimension(200, 40));
        btnCourseManagement.setMinimumSize(new java.awt.Dimension(20, 23));
        btnCourseManagement.setPreferredSize(new java.awt.Dimension(240, 30));
        btnCourseManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseManagementIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnProfileManagement.setBackground(new java.awt.Color(102, 153, 255));
        btnProfileManagement.setFont(getFont());
        btnProfileManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnProfileManagement.setText("Profile Management");
        btnProfileManagement.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProfileManagement.setMaximumSize(new java.awt.Dimension(200, 40));
        btnProfileManagement.setMinimumSize(new java.awt.Dimension(20, 20));
        btnProfileManagement.setPreferredSize(new java.awt.Dimension(240, 25));
        btnProfileManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileManagementActionPerformed(evt);
            }
        });

        btnStudentManagement.setBackground(new java.awt.Color(102, 153, 255));
        btnStudentManagement.setFont(getFont());
        btnStudentManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnStudentManagement.setText("Student Management");
        btnStudentManagement.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStudentManagement.setMaximumSize(new java.awt.Dimension(145, 40));
        btnStudentManagement.setMinimumSize(new java.awt.Dimension(20, 20));
        btnStudentManagement.setPreferredSize(new java.awt.Dimension(240, 25));
        btnStudentManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentManagementIdentifyEventsActionPerformed(evt);
            }
        });

        btnPerformance.setBackground(new java.awt.Color(102, 153, 255));
        btnPerformance.setFont(getFont());
        btnPerformance.setForeground(new java.awt.Color(255, 255, 255));
        btnPerformance.setText("Performance Reporting");
        btnPerformance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPerformance.setMaximumSize(new java.awt.Dimension(200, 40));
        btnPerformance.setMinimumSize(new java.awt.Dimension(20, 20));
        btnPerformance.setPreferredSize(new java.awt.Dimension(240, 25));
        btnPerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformanceActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("My Faculty Profie");

        btnTution.setBackground(new java.awt.Color(102, 153, 255));
        btnTution.setFont(getFont());
        btnTution.setForeground(new java.awt.Color(255, 255, 255));
        btnTution.setText("Tution Enrollment");
        btnTution.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTution.setMaximumSize(new java.awt.Dimension(145, 40));
        btnTution.setMinimumSize(new java.awt.Dimension(20, 20));
        btnTution.setPreferredSize(new java.awt.Dimension(240, 25));
        btnTution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutionIdentifyEventsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnCourseManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(75, 75, 75)
                                    .addComponent(btnProfileManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnStudentManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(btnTution, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(632, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourseManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProfileManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(btnTution, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseManagementIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseManagementIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.removeAll();

    CourseManagementJPanel cmp = new CourseManagementJPanel(business, facultyProfile, CardSequencePanel);  

    CardSequencePanel.add("Course Management", cmp);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnCourseManagementIdentifyResourceAssetsActionPerformed

    private void btnProfileManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileManagementActionPerformed
        // TODO add your handling code here:

  
    }//GEN-LAST:event_btnProfileManagementActionPerformed

    private void btnStudentManagementIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentManagementIdentifyEventsActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.removeAll();
        //    IdentifyEventTypes iet= new IdentifyEventTypes(businessunit, CardSequencePanel);

        //    CardSequencePanel.add("IdentifyEventTypes", iet);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        //((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");
}//GEN-LAST:event_btnStudentManagementIdentifyEventsActionPerformed

    private void btnPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformanceActionPerformed
        // TODO add your handling code here:

}//GEN-LAST:event_btnPerformanceActionPerformed

    private void btnTutionIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutionIdentifyEventsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTutionIdentifyEventsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseManagement;
    private javax.swing.JButton btnPerformance;
    private javax.swing.JButton btnProfileManagement;
    private javax.swing.JButton btnStudentManagement;
    private javax.swing.JButton btnTution;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
